i_crit: 10                #[mkA]
i_bias: 3                 #[mkA]
i_osc: 0                  #[double, part of i_crit]
i_vel: 0                  #[mkA/s]
resistance: 30            #[Ohm]
capacity: 2.65            #[pF]
freqency: 0               #[Hz]
temp: 100                 #[mK]
snd_harm: 0               #[double]
t_max: 100000             #[double]
t_step: 0.5               #[double]
sw_count: 2000            #[int]
scd_flag: 1               #[int]
out_file_name: file       #[string]
iterable: i_bias          #[string, parameter to iterate]
step: 0.1                #[double, step of iterable parameter]
#points: 4                 #[int, num of iterations]